name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        source $HOME/.cargo/env

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install googletrans==4.0.0rc1
        pip install tokenizers

    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests..."
